/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 forklift.glb 
Author: Ricardo Sanchez (https://sketchfab.com/380660711785)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/forklift-low-poly-8ab650b3982243f8b661142de50f79c9
Title: Forklift low poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ForkModel(props) {
  const { nodes, materials } = useGLTF('/forklift.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Loader_car_Loader_car_Material_0.geometry} material={materials.Loader_car_Material} position={[0.003, 0.386, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/forklift.glb')
