/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 f22.glb 
Author: andertan (https://sketchfab.com/andertan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lockheed-martin-f-22-raptor-7e7b3c372e374dda98e70208d09cfdcf
Title: Lockheed Martin F-22 "Raptor"
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function F22model(props) {
  const { nodes, materials } = useGLTF('/f22.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.842, 0.392, -0.001]} rotation={[0, 0, 0.082]} scale={[0.086, 0.096, 0.096]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Darkness.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Whitish_grey.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Nato_black} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Darker_paint.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Whitish_grey.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Glowing_green.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['screen.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.f22_top_U} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.f22_bottom_L} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.f22_top_D} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['f22_bottom_R.']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.dark} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.f22_bottom_L_darker} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.f22_bottom_R_darker} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.plumes} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.plumes_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/f22.glb')
